### PR TITLE
Build corrections

### PR DESCRIPTION
**Pull request by ednaldomoreira**

### CODE REVIEW

**Comment by StefanWerW** [comment]
Ed, @ednaldomoreira  o arquivo .pullapprove.yml que voce colocou ta dando pau

**Comment by ednaldomoreira** [comment]
@StefanWerW eu estou tentando configurar para pegar o team Desenvolvimento

Pela documentação ele deveria aceitar trocar o 'members' pelo 'teams'

teams
Possible values: array of team slugs
The GitHub teams whose members make up this reviewer group. Be sure to use the slug (lowercase, hyphenated) for the team names.

A reviewer group must use either members or teams, but not both.

**Comment by ednaldomoreira** [comment]
@StefanWerW veja aí se ficou ok

**Comment by guilhermercaetano** [comment]
Approved.

[Approved with PullApprove](https://pullapprove.com/MuvucaGames/MuvucaGame01/pull-request/243/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=MuvucaGames/MuvucaGame01)

**Pull request merged**
